apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: ruma-moe
data:
  prometheus.yml: |
    global:
      scrape_interval: 5s
    scrape_configs:
      - job_name: 'ruma-moe'
        static_configs:
          - targets: ['backend:8080']
